baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Davitogo"
theme = "davitogo"


[outputFormats]
  [outputFormats.print]
    baseName = "index"
    isHTML = true
    mediaType = "text/html"
    permalinkable = false