baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Davitogo"
theme = "davitogo"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
DefaultContentLanguage = "en"
# disable pluralise 
pluralizeListTitles = false

[Author]
name = "David Mullins"
email = "me@davit.ie"
#  facebook = "username"
#  googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
gitlab = "DavitTec"
github = "DavitTec"
twitter = "_Davit"
#  reddit = "DavitTec"
linkedin = "davidpmullins"
#xing = "username"


[build]
duplicateResourceFiles = false
noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'
[build.buildStats]
disableClasses = false
disableIDs = false
disableTags = false
enable = false
[[build.cacheBusters]]
source = '(postcss|tailwind)\.config\.js'
target = '(css|styles|scss|sass)'

[Params]
version = "0.0.3"
subtitle = "Davit Blog Template for Github Pages"
logo = "img/logo.png"
favicon = "img/favicon.ico?v=2"
dateFormat = "January 2, 2006"
commit = false
rss = true
comments = true


[outputFormats]
[outputFormats.print]
baseName = "index"
isHTML = true
mediaType = "text/html"
permalinkable = false


[languages]
  [languages.de]
    languageCode = 'de-DE'
    languageName = 'Deutsch'
    weight = 1
  [languages.en]
    languageCode = 'en-UK'
    languageName = 'English'
    weight = 2